version: '3'

services:
  ui:
    container_name: thomosis-ui
    image: devopseasylearning/thomisis-ui:v0.0.1
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    expose:
      - 3000 
    ports: 
      - 3000:3000
    networks:
      - thomisis
    restart: always
    depends_on: 
      - auth
    

  auth:
    container_name: thomosis-auth
    image: devopseasylearning/thomisis-auth:v0.0.1
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    expose:
      - 8080
    networks:
      - thomisis
    restart: always
    depends_on : 
      - weather
    volumes:
      - user-data:/var/lib/userdata

  weather:
    container_name: thomosis-weather
    image: devopseasylearning/thomisis-weather:v0.0.1
    expose:
      - 5000
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - thomisis
    restart: always
    depends_on : 
        - db 
        - redis 
    volumes: 
    - weather-data:/var/lib/weatherdata


  db:
    container_name: thomosis-db
    image: mysql:8.1 #devopseasylearning/thomisis-db:v0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - thomisis
    restart: always
    ports: 
      - 3306:3306
    volumes:
       - db-data:/var/lib/db

  redis:
    container_name: thomosis-redis
    image: redis
    networks:
      - thomisis
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    ports: 
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

networks:
  thomisis:
volumes:
  db-data:
  weather-data:
  user-data:
  redis-data: