apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configname }}
data:
  AUTH_HOST: "auth"
  AUTH_PORT: "8080"
  WEATHER_HOST: "weather"
  WEATHER_PORT: "5000"
  REDIS_USER: "cmVkaXM="
  REDIS_PASSWORD: "cmVkaXM="
